# Generated by Django 5.1.5 on 2025-05-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0006_book_author_book_description_book_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pic_path',
        ),
    ]
