# Generated by Django 5.2 on 2025-05-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0009_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='web',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
