# Generated by Django 5.2 on 2025-05-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_remove_book_web_alter_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
