# Generated by Django 5.2 on 2025-05-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0011_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='format',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
